### ISSUE TITLE
Intro to eml2 development

### ISSUE THREAD

**Issue by cboettig** [cboettig/eml2#1]
Hey @mbjones ,

Wondering if you can take a look at this package when you get a chance.  Still very bare-bones but always best to fix structural issues early.  As I mentioned to you before, my goal here is to generate classes for the full EML schema programmatically from the schema files.  This has basically meant me just reading the `.xsd` files and hacking away at tricks to pull out the information needed to create the S4 class definitions. Given my very imperfect knowledge of XSD schema rules, this is somewhat dodgy, but I think still more consistent & comprehensive than the manual approach in `EML` R package.  You can see the 'rules' I've come up with for extracting class definitions from XSD here: https://github.com/cboettig/eml2/blob/9f42e05800e45e269b83a5a96f0c029a1a3cab60/inst/create-package/xsd_classes.R#L199-L247  

These have been built largely on a  trial-an-error basis.  One of the things I found most challenging was how to construct the appropriate XPATH expression to get all the child elements for a class (e.g. things that become the S4 slots) without getting children of those child elements.  This is tricky because there can be quite a variable number of "indicator" elements (`<xs:choice>`, `<xs:select>`) etc between an `<xs:complexType>` and its corresponding `<xs:element>` children, see https://github.com/cboettig/eml2/blob/9f42e05800e45e269b83a5a96f0c029a1a3cab60/inst/create-package/xsd_classes.R#L134

I have largely followed the same conventions as in the `EML` package for creating a mapping between XML and S4 objects, though applied more rigorously (no more short-cuts of ignoring repeatable elements or just making something a character class).  That is roughly: 

1. S4 slot names match element child names and element attribute names
2. The slot class matches the element `type`, except if
3. A child element can appear multiple times, then the S4 slot is of class `ListOf<type>`, which inherits from list, 
4. All attribute slots are of class `xml_attribute`, which inherits the "character" class
5. the S4 class inherits (`contains=`) any `xs:group` `ref` and any `xs:extension` `base` (maybe that's sensible??)

I've been tweaking these rules as I find EML that doesn't parse.  So far I've actually implemented only a [single test](https://github.com/cboettig/eml2/blob/9f42e05800e45e269b83a5a96f0c029a1a3cab60/tests/testthat/test-party.R) based on a [test file]https://github.com/cboettig/eml2/tree/9f42e05800e45e269b83a5a96f0c029a1a3cab60/inst/xsd/test)  you ship with the EML distribution already, but it should be quick for me to add similar tests for all the remaining test files provided there.  For now, that test should illustrate the very minimal functionality of parsing arbitrary EML into S4, and serializing that S4 back into EML.  Once that backbone is solid, all the rest should be rather straight-forward.

**Comment by mbjones** [comment]
@cboettig Wow, you are fast sometimes :)  I gave it a quick look, and seems like it could work.  XSD is a complex spec, though, and I think your parsing could be missing some of the subtleties.   The two things I see missing are 1) `xsd:group` definitions, and 2) links between ListOf* classes and the types of their contained children. 

The `xsd:group` approach is used in several places in EML to inject a common structure into multiple complex types, such as using ResourceGroup in multiple types of entities.  You seem to have found the elements, sequences, etc inside of these, but missed defining the group itself as a class, although I could have missed it.  For example, I find `contains='ResourceGroup"` throughout, but I don't find the `setClass` statement for `ResourceGroup` itself.  Did I miss it?

Regarding ListOf*, it looks like the lists are created, but they are of plain type list, and don't have any connection to their contained element types.  It would be nice to have something like Java's Generics for list types in R, but I'm not sure if it exists.  For example, you create:

```R
setClass('ListOfuserId', contains = 'list')
setClass('userId', slots = c('directory' = 'xml_attribute'), contains = c('xs:string', 'eml-2.1.1'))
setClass('ResponsibleParty', slots = c('individualName' = 'Person', 'organizationName' = 'character', 'positionName' = 'character', 'address' = 'ListOfaddress', 'phone' = 'ListOfphone', 'electronicMailAddress' = 'ListOfelectronicMailAddress', 'onlineUrl' = 'ListOfonlineUrl', 'userId' = 'ListOfuserId', 'id' = 'xml_attribute', 'system' = 'xml_attribute', 'scope' = 'xml_attribute'), contains = c('ReferencesGroup', 'eml-2.1.1'))
```

But there is no link stating that `ListOfuserId` must be a class containing instances of `userId`. Not sure there is a solution to this.  And if there isn't, it seems it might be no better than just having all repeating elements contain list itself. Deserves further discussion.

It will take more time for me to look at this in detail.  Glad your so willing to see this through!

**Comment by cboettig** [comment]
Thanks!

Great question about `xsd:group`. Looks like I never grabbed `xs:group[@name]` elements to actually declared those classes; even though I was already picking up `xs:group[@ref]` instances as `contains`, https://github.com/cboettig/eml2/blob/9f42e05800e45e269b83a5a96f0c029a1a3cab60/inst/create-package/xsd_classes.R#L146  .  Now fixed.  

Re: `ListOf*`, you're dead on, these are plain-type lists.  When I've seen Duncan do this, he adds a `validity` declaration to the `setClass` call which checks that all the objects in the list have the appropriate class.  I've chosen to leave this off for now -- it will make the codebase even larger and a bit slower, (and it's not the only place where we are not strict about type -- the current pass has no `validity` checks for any of the classes; which is something we might add later but for now might leave to checking EML).  I can definitely add that validity check though.   

Not sure I follow how having a repeating element contain `list` itself would work.  One advantage of the current construction is that S4 indexing can work in the R-like manner of `node@element[[3]]@stuff`.  

Another downside of the `ListOf` use is that the `new` constructor becomes more ugly.  However, I think we can fix this by defining custom initialize methods.  Will open a new issue with an example of that.

**Comment by cboettig** [comment]
The schema translation to S4 and back may still not be failproof, as discussed in #3 there are some things you can do in XSD that are not so trivial in S4, so some of this is heuristic.  Yet I think it is safe to say at this stage that `eml2` can handle much closer to 100% of valid `eml-2.1.1` schema-compliant files than our original `EML` R library can.  

Two limitations worth noting: 

-  I have made `textType`, `para` and `section` nodes inherit from `InlineType` to allow them to take arbitrary XML.  It's not clear that it would ever be useful to work with the DocBook subset objects as S4 objects (e.g. a class with separate slots for 'text' and 'emphasized' and 'orderedList' etc).  It would seem much more natural to work with them in XML, and I believe Duncan already has sophisticated tools to do so in Rdocbook.  

- The S4 representation treats certain Types like `ResourceGroup` as an explicit slot rather than the more obvious method of inheriting those slots directly via `contains()`.  This helps ensure slot order obeys the schema (I suppose I could have added some additional data element to the class to dictate the XML order instead...), but despite seeming cumbersome at first it does make it easier to reuse or move around those groups of related slots, so for some R manipulations this is actually quite convenient I think.  

I've added some basic information in the README file.  Only functions so far are `write_eml()`, `read_eml()`, and `eml_validate()`.  As mentioned in #5, there are also custom `initialize` methods (`new()`) for any item that involves a `ListOf`, so these constructors are reasonably concise.  I'll still add helper functions to do the more annoying constructions like an attributeList.

**Comment by cboettig** [comment]
`eml2` now merged into `ropensci/EML`
