### ISSUE TITLE
Implement function to assist in parsing and creating an attributeList

### ISSUE THREAD

**Issue by cboettig** [cboettig/eml2#11]
EML provided `eml_attributeList()` (https://github.com/ropensci/EML/blob/master/R/eml_attributeList.R) to help in generating an attributeList element.  This is one of the more essential helper functions.  

This function took somewhat stylized arguments that permitted only a minimal definition for each attribute (column definition values, minimal measurementScale information).  Likewise it's complement function for parsing EML returned similarly minimal information in a somewhat arbitrary list format.  The appropriate mapping for formats here deserves closer attention.

**Comment by cboettig** [comment]
[this script](https://github.com/cboettig/eml2/blob/b688b48635874de7a30312dbaa31489bd899eeae/inst/examples/attribute_list.R) shows one example of how we might parse the complex attributeList from [eml-datasetWithAttributelevelMethods.xml](https://github.com/cboettig/eml2/blob/master/inst/xsd/test/eml-datasetWithAttributelevelMethods.xml) into corresponding data.frames, e.g.

A data.frame with attribute metadata:

```
att_df
Source: local data frame [12 x 6]

      name                             label   type missing    scale
     (chr)                             (chr)  (chr)   (lgl)    (chr)
1      fld                             Field string      NA  nominal
2     year                              year  gYear      NA dateTime
3       sr                  Species Richness  float      NA interval
4   pctcov                     percent cover  float      NA    ratio
5  avesr91 Average Species Richness for 1991  float      NA    ratio
6  avesr92 Average Species Richness for 1992  float      NA    ratio
7  avesr93 Average Species Richness for 1993  float      NA    ratio
8  avesr94 Average Species Richness for 1994  float      NA    ratio
9  avesr95 Average Species Richness for 1995  float      NA    ratio
10 avesr96 Average Species Richness for 1996  float      NA    ratio
11  MeanSR             mean species richness  float      NA    ratio
12    time                              Time   time      NA dateTime
Variables not shown: def (chr)
```

And a separate data.frame for unit metadata (ratio/interval types):

```
units_df
Source: local data frame [9 x 6]

     name          unit precision  type lower_bound upper_bound
    (chr)         (chr)     (chr) (chr)       (chr)       (chr)
1      sr dimensionless       0.5  real           0          NA
2  pctcov dimensionless       0.1  real           0         100
3 avesr91 dimensionless       0.1  real           0          NA
4 avesr92 dimensionless       0.1  real           0          NA
5 avesr93 dimensionless       0.1  real           0          NA
6 avesr94 dimensionless       0.1  real           0          NA
7 avesr95 dimensionless       0.1  real           0          NA
8 avesr96 dimensionless       0.1  real           0          NA
9  MeanSR dimensionless       0.1  real           0          NA
```

We might make similar data frames for the factor (nominal/ordinal) elements and time elements.

This mapping could be reversed then as a fast way to build a more thorough attributeList.

@mbjones Is this a reasonable way to go? Or is this crazy?  Would something more minimal be better?

**Comment by mbjones** [comment]
@cboettig It looks reasonable.  As the `att_df` and `units_df` are both keyed on name, I'm not sure why we need two separate data frames -- they could be combined.  Using a table as a way to collate the attribute metadata seems natural to me, as that is largely how we display it to users as well. For display, we often transpose it, but I think having it as you describe makes sense.  The separate table for the nominal/ordinal enumerated value lists makes sense, as those would be one to many levels where you need both the code and definition to be represented for each level of a factor.

**Comment by amoeba** [comment]
Hey @cboettig, @mbjones shared this issue with me. This doesn't look crazy at all. An alternative could be to use lists but I, as an end-user, would much rather work with a data frame. A big win is how easy it is to see it all at once.

**Comment by cboettig** [comment]
Thanks!  Yup, can definitely join on the attribute name.    The fully joined table might look a bit huge, but i agree it would be useful.  In particular, for factor data (nominal/ordinal enumeratedType), the table would probably repeat the key value since we have a list of code/definition pairs for each possible value in the factor.  (Or is there a better alternative for that case?)

**Comment by mbjones** [comment]
@cboetig I was thinking of two normalized tables, one for attribute
metadata, and one with enumerated values with a foreign key to attributes.

We could then have a print function that nicely joined these and displayed
these for any given attribute, or returned a joined data structure. Some
accessor methods that easily allowed one to inspect and modify attribute
metadata, as well as add new attributes in the data frames would be useful.
Reordering the list would be good too.  It would also be nice to apply an
attributeList to more than one data frame, which is common.  Nice work so
far @cboettig

**Comment by cboettig** [comment]
@mbjones breaking the enumeratedValues into a separate table with a foreign key while joining the rest sounds good.  

### Other issues in mapping attributeList to a data.frame

There's a bunch of cases where an attribute element can use a given element multiple times (though often it's not clear to me what repeated use would mean).  

- [ ] What does it mean (or what is the use case) to have multiple `<bounds>` elements for a single attribute (e.g. repeating `<bounds>` elements inside a numericDomain element?  Currently in mapping to data.frame I assume any attribute has at most one bounds element -- that is, we have attribute names as row keys, and a column for max bound and min bound (which gives NA if not given, as illustrated above).  Is that okay even though technically EML can have repeated bounds elements?  

- [ ] Likewise, attributes can have multiple labels, multiple missingValue symbols.  Are we good enough taking just the first one?  Or should we be creating extra columns in this case? (I don't really like the idea of the function returning a variable number of columns)

- [ ] It looks like a single given attribute can have multiple textDomain (or multiple enumeratedDomain) elements?  What would the use case for that be?  How do we handle mapping those?

**Comment by mbjones** [comment]
@cboettig 

- Repeating `<bounds>` elements allow for discontinuous domains for variables; probably rare, and an edge case
- Multiple labels are just for display. In general, it would be good to preserve them
- Multiple missing value symbols are critical to preserve; it is really common to have different missing value codes in a data set (e.g., to represent different error conditions (-1 == sensor failed, -2 = sensor obscured, ...), and these need to be both preserved and editable in the eml2 package
- `<nonNumericDomain>` is a repeating choice of `<enumeratedDomain>` and `<textDomain>`, which allows one to define an attribute whose domain is the union if multiple controlled vocabularies and uncontrolled text.  For example, one might have an attribute that uses any value from the FIPS State codes or the ISO 2-letter country codes; or one that supports FIPS state codes, or any free-text name of a state; validators need to know what the full domain definition represents;
    - the most difficult thing you'll probably encounter is when an enumeratedDomain for an attribute is defined by the values in some column in a lookup table in the package, which is defined in the `<entityCodeList>` element; this is often done when many attributes share the same enumerated domain

**Comment by cboettig** [comment]
@mbjones Thanks, super helpful, really great to have your depth of experience in informing this.  And thanks for pushing back in any cases where I don't grok the use case and/or oversimplify.

Regarding the repeating elements, definitely all of this data is preserved and editable in the S4 format, even the rarer cases like multiple bounds.  (Since the S4 R classes are generated automatically from the schema, it is actually the R classes themselves that I'm using to realize that things like `<bounds>` use repeating elements).  

The only question here is what to do about mapping this information to a table format using the `get_attributes()` function.  Hopefully we can communicate to users that this function is only a convenience function for extracting data from a lot of different (but related) EML elements at once and returning it as a `data.frame` (or vice versa), but being aware that it is not the only way in R to access and manipulate attribute metadata.  I'm guessing there will always be more information represented in the nested XML or S4 format that cannot easily be mapped into a convenient number of data frames, but maybe I'm wrong about that. I think the trick here is in designing these convenience functions trade-off a bit of richness for something that's a bit easier to manipulate and to reason about without detailed familiarity with the full EML schema.  

So for instance, for the multiple labels or multiple missing values, this data is available in R using the `@` subsetting, I'm just not sure how to map it into a data.frame.  The examples I showed above had a column for 'missing' code for instance.  I suppose we could just add additional missing codes as additional columns, but I would much prefer that the function returned a data.frame with consistent columns to make programming with it easier.  Does that make sense?

Thanks for the heads up about entityCodeList; haven't coded the enumeratedDomain part yet.  Not quite sure I understand how entityCodeList works.  Does that mean that the code definitions aren't in the XML but exist in some external file?  Can you point me to an example of entityCodeList?  

I did implement the 'references' look-up for re-using element definitions in the other types, which was much more straight forward; though I'm not sure I completely understand the rules for `<references>`.  They can refer to any `id` anywhere in the document? (or perhaps in the `scope` of they inherit from their parent element?)  Ironically the code to do this lookup is pretty slow since I serialize back to XML to use an XPath expression to find the element with matching `id` attribute in the document.  Maybe it would be faster to recursively search the S4 objects instead, but "find anywhere" seems like a more natural thing for xpath than for nested lists.

**Comment by mbjones** [comment]
@cboettig Yeah, your thoughts on the attributeList make sense, and are heading in a good direction.

The `<entityCodeList>` points at a table in the current EML package that contains the codes and their definitions.  So, it contains three fields which point to the id of the entity (table) containing the list, the id of the attribute containing the code value, and the id of the attribute containing the code definition.  So, I might have a table entity in my package called 'speciesCodes, and it might have an attribute called sppCode and another called bionomial, and these would be referenced in the entityCodeList to provide the value list for the domain of another table that uses those species codes.  The idea was that this is common for really long code lists like species lists that tend to be data-set specific.  We support this structure in Morpho, but its complicated to set up, and I'm not sure how often it has been used. Here's an example of its use from PISCO:  
- https://knb.ecoinformatics.org/knb/d1/mn/v2/object/doi:10.6085/AA/pisco_barnacle_fecundity.2.2

For references, yes they can refer to any `id` anywhere in the document, but the `id` must be present - a dangling reference is considered an invalid EML document, although that is only checked by the EML parser, and not XSD schema (complicated history there).

**Comment by cboettig** [comment]
Okay, `set_attributes()` and `get_attributes()` methods are now implemented.  Can probably be refined more, in particular, `set_attributes()` could do much more to help a user know what columns must be included.  Working out a few use-cases should help illustrate the best design for this; see [hf-205.R](https://github.com/ropensci/EML/blob/master/inst/examples/hf-205.R)

**Comment by ivanhanigan** [comment]
@cboettig I am very excited to see the burst of activity here.  Thanks.
Re https://github.com/ropensci/EML/blob/master/inst/examples/hf-205.R#L50 (`attributes <- ...`) I'd like to see a function that derives this from the data.frame with as much automation as possible.  Something like `str()` on steroids.
Then https://github.com/ropensci/EML/blob/master/inst/examples/hf-205.R#L92 (`factors <- `) If this could also be generated by a helper function like `levels()` on steroids... or `papeR::summarize()`.

For eg.

```r
# we are using the hf205 dataset, I have this hanging around an old clone of the EML repo
ds <- read.csv("~/tools/EML/inst/examples/hf205-01-TPexp1.csv")
# papeR has a nice summary tool
library("devtools")
install_github("hofnerb/papeR")
papeR::summarize(ds[,c("i.flag","variable")], type  = "factor")
##                  Level        N    %
## 1    i.flag          B      472  0.2
## 2                    I     7696  2.8
## 3                    R   271056 97.1
## 4  variable   air.temp    34903 12.5
## 5              control    34903 12.5
## 6                 high    34903 12.5
## 7                  low    34903 12.5
## 8             med.high    34903 12.5
## 9              med.low    34903 12.5
## 10                 par    34903 12.5
## 11          water.temp    34903 12.5
```

I can imagine doing some cleaning, recoding, imputation, create some new levels or even new variables etc etc...
then run some similar function to generate the required names and levels then add some definitions and write the results to an EML.

My imagined workflow is similar to the flow chart you published in Boettiger, C., Chamberlain, S., Hart, E., & Ram, K. (2015). Building Software, Building Community: Lessons from the rOpenSci Project. Journal of Open Research Software, 3(1). doi:10.5334/jors.bu

where the link between `generate clean dataset and metadata` and `permanent repository` is as simple as running a few helper functions and then filling in a couple additional definitions and explanations here and there.
