### ISSUE TITLE
`get_attributes` warning message

### ISSUE THREAD

**Issue by isteves** [cboettig/eml2#11]
When an attributeList does not have any enumerated domains (factors), the function throws this warning:

```
Warning messages:
1: Unknown or uninitialised column: 'code'. 
2: In is.na(factors$code) :
  is.na() applied to non-(list or vector) of type 'NULL'
```

It looks like [this line](https://github.com/cboettig/eml2/blob/468f719c7dd5fada3a0a8482c140f8e32139c0c2/R/get_attributes.R#L89) is to blame: `factors <- factors[!is.na(factors$code), ]`

Changing it to `factors <- ifelse(length(factors) == 0, NULL, factors[!is.na(factors$code), ])` (or something like it) should solve the problem

**Comment by maier-m** [comment]
https://github.com/cboettig/eml2/pull/12 should have fixed this
