### ISSUE TITLE
schema namespace issues

### ISSUE THREAD

**Issue by cboettig** [cboettig/eml2#2]
@mbjones There's some pretty challenging namespacing issues that can arise here, maybe you can suggest some clever work-arounds. 

For instance, it appears that element names in the EML schema are not unique, e.g. an `<online>` node can appear in an EML document with different class depending on if it's in a `<physical>` node or a resource-type node.

Unfortunately my S4 strategy is not this clever; it just declares a class based on the name of the element, and all classes are declared in the package environment (or global environment if you source'd the `classes.R` instead of installing the package).  This means that the class `online` as defined in the `eml-resource.xsd` schema gets over-written by that defined in `eml-physical.xsd` and thus we cannot parse occurrences of the former, like: https://github.com/cboettig/eml2/blob/master/inst/xsd/test/eml.xml#L26

`setClass` does let you declare an environment via `where` argument (though the docs say: "Should not be supplied in standard use.")  , so potentially we could try and define classes in xsd-specific environments, but then I'm scratching my head as to how we'd actually use such classes.  Doesn't look like this is designed to work that way.

**Comment by cboettig** [comment]
The documentation for `setClass` also says:

> In rare cases where there is ambiguity about the class of a slot, because two classes of the same name are imported from different packages, the corresponding element of the argument must have a "package" attribute to disambiguate the choice.

It's not clear to me how this actually works (e.g. what the syntax for this should look like -- they don't give an example).  It does suggest that we could make a package for each XSD file, since separation into seperate "packages" seems to be the only way to namespace classes in S4.  That does feel rather desperate though.

**Comment by cboettig** [comment]
No perfect fix for this, but there are not too many collisions so I have just opted to work around them with some post-processing (see `inst/create-package`) of the classes generated by the schema.  (Similar post-processing helps avoid namespace collisions with protected classes in R that are also EML elements, like `array`, `list`, `matrix`, `complex` etc.)

**Comment by mbjones** [comment]
@cboettig I don't have any major suggestions for this, and your post-processing seems reasonable.  EML makes extensive use of the XML hierarchy to indicate context for metadata, so the 'creator' element is sometimes the creator of a dataset, sometimes the PI on a project, and sometimes the author of a citation, all depending on the nested context.  One thing you could consider, although I'm skeptical about this working universally, is to use the context in the class name, such that datasetCreator and projectCreator would be different classes.  I'll give your solution a try when I jump in here.

**Comment by cboettig** [comment]
@mbjones right, but I don't think that's a problem since a `creator` element in a dataset or in a citation is still the same structure (e.g. inherits from `ResponsibleParty`) so it's easy to construct a consistent definition for the class.  That class can then be nested into wherever it is appropriate.  I don't think any of the schema have an element named 'creator' that is a totally different `xs:type` rather than being `ResponsibleParty`, right?

The only time namespaces are a bigger problem is when EML defines two elements with identical names but very different types.  For instance, I think the `eml-physical.xsd` and `eml-resource.xsd` both provide definitions for an element with name "online" but with different definitions (that is, with different `xs:type` or different permissible attributes or child elements).  Likewise there's a definition for an element called `geographicCoverage` in the literature module which is different from the definition in the coverage module.  These collisions are rare though so I've just worked around them manually.

**Comment by mbjones** [comment]
@cboettig You're right about the types being consistent, but EML does make use of extension. So, for example, while `creator` is of type `ResponsibleParty`, the element `associatedParty` is an extension of `ResponsibleParty` that adds the `role` field.

**Comment by cboettig** [comment]
Right, I know, that also doesn't pose any problem: we just inherit the base
type and add a slot, since "associatedParty" element is only defined once
we don't need to worry if it is the element of that name that appears in
one module/xsd file or another.  Collisions are only an issue when element
names are not unique

On Wed, Feb 17, 2016, 4:32 PM Matt Jones <notifications@github.com> wrote:

> @cboettig <https://github.com/cboettig> You're right about the types
> being consistent, but EML does make use of extension. So, for example,
> while creator is of type ResponsibleParty, the element associatedParty is
> an extension of ResponsibleParty that adds the role field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cboettig/eml2/issues/2#issuecomment-185478316>.
>
-- 

http://carlboettiger.info
