### ISSUE TITLE
eml_validate should work on R objects as well

### ISSUE THREAD

**Issue by cboettig** [cboettig/eml2#2]
e.g. this should work:

```r
eml <- read_eml(f)
eml_validate(f)
```

currently only this works:

```r
eml_validate(f)
```

also should provide more intelligent error messages when wrong type of object is passed to `eml_validate`.

Thanks @isteves for catching these.

**Comment by isteves** [comment]
Hey @cboettig, is there a way I can help with ^ (or other `eml2` to-do's)?  Since we're using EML pretty heavily at NCEAS, I'd like to dive deeper into the EML R package of the future!

**Comment by cboettig** [comment]
Thanks @isteves .  This one is now fixed in 097abf66ffe53714e253b94451b457125972de35 (requires the latest version from `emld`, though `install_github("cboettig/eml2")` should pull that in automatically).

I think most of the bits here should be at or beyond what is in `EML` R package, but could use a bit more testing.  As I mentioned, my goal is for this one to be much easier to use, ideally even for people that don't have a  lot of familiarity with the EML metadata fields.  So definitely file more issues like the one above where you find things that seem like they should work but don't!
