### ISSUE TITLE
Implement all tests in /inst/xsd/test

### ISSUE THREAD

**Issue by cboettig** [cboettig/eml2#4]
Add unit tests to make sure we can accurately parse & re-serialize all of the example EML snippets provided in the original EML test suite see [/inst/xsd/test](https://github.com/cboettig/eml2/tree/master/inst/xsd/test).

**Comment by cboettig** [comment]
Tests now implemented in https://github.com/cboettig/eml2/blob/master/tests/testthat/test-testfiles.R 
Could use extending to actually test more things (e.g. serialize to minimal eml and validate).

**Comment by cboettig** [comment]
@mbjones Okay, all of the `eml-*.xsd` files you had provided in `xsd/test` can now be parsed by `eml2`, serialized, and validated against the schema.  The check also confirms that the element list in the resulting output is identical to that of the original file; which further makes sure we have not lost any elements in the translation.

**Comment by mbjones** [comment]
@cboettig Awesome.
