### ISSUE TITLE
port get_attributes function

### ISSUE THREAD

**Issue by maier-m** [cboettig/eml2#8]
In the EML package `get_attributes` was a very useful function that has not yet been ported.
Is there a clever reason why not?
If not can assist with creating eml2 variety.

**Comment by cboettig** [comment]
good catch, apparently I didn't notice that I hadn't finished porting `get_*` methods.  Yeah, a PR on that would be great.  (You can probably implement it without `eml_get` but of course it would be nice to fix #7... stay tuned)
